site_name: Bpipe
repo_url: https://github.com/ssadedin/bpipe
theme: readthedocs
extra_css: [extra.css]
nav:
- Overview:
  - Introduction: Overview/Introduction.md
  - Comparison To Workflow Tools: Overview/ComparisonToWorkflowTools.md
  - Install Instructions: Overview/InstallInstructions.md
- Language:
  - About: Language/About.md
  - Check: Language/Check.md
  - Chr: Language/Chr.md
  - Cleanup: Language/CleanupStatement.md
  - Config: Language/Config.md
  - Debug: Language/Debug.md
  - Directories: Language/Directories.md
  - Doc: Language/Doc.md
  - Exec: Language/Exec.md
  - Fail: Language/Fail.md
  - File: Language/File.md
  - Filter: Language/Filter.md
  - Forward: Language/Forward.md
  - From: Language/From.md
  - Glob: Language/Glob.md
  - Grep: Language/Grep.md
  - Load: Language/Load.md
  - Merge Point Operator: Language/MergePoints.md
  - Multi: Language/Multi.md
  - Output: Language/Output.md
  - Options: Language/Options.md
  - Prefix: Language/Prefix.md
  - Produce: Language/Produce.md
  - R: Language/R.md
  - Segments: Language/Segments.md
  - Send: Language/Send.md
  - Succeed: Language/Succeed.md
  - Transform: Language/Transform.md
  - Using: Language/Using.md
  - Preserve in pipeline: Language/PreserveInPipeline.md
  - requires: Language/requires.md
  - uses: Language/uses.md
  - var: Language/var.md
- Commands:
  - Using the bpipe command: Commands/Commands.md
  - cleanup: Commands/cleanup.md
  - execute: Commands/execute.md
  - history: Commands/history.md
  - jobs: Commands/jobs.md
  - log: Commands/log.md
  - preserve: Commands/preserve.md
  - query: Commands/query.md
  - retry: Commands/retry.md
  - run: Commands/run.md
  - status: Commands/status.md
  - stop: Commands/stop.md
  - test: Commands/test.md
- Tutorials:
  - Hello, World: Tutorials/Hello,World.md
  - Example With Inputs And Outputs: Tutorials/ExampleWithInputsAndOutputs.md
  - Real Pipeline Tutorial: Tutorials/RealPipelineTutorial.md
- Guides:
  - Configuration Support: Guides/Configuration.md
  - Variables: Guides/Variables.md
  - Parallel Tasks: Guides/ParallelTasks.md
  - Branch Variables: Guides/BranchVariables.md
  - Extension Syntax: Guides/ExtensionSyntax.md
  - Logging: Guides/Logging.md
  - Modules: Guides/Modules.md
  - Notifications: Guides/Notifications.md
  - Working with Genomic Regions: Guides/Regions.md
  - Reports: Guides/Reports.md
  - Resource Managers: Guides/ResourceManagers.md
  - Tool Version Database: Guides/ToolVersionDatabase.md
  - Trash: Guides/Trash.md
  - Development Setup: Guides/DevelopmentSetup.md
  - Documentation Style: Guides/DocumentationStyle.md
  - Implementing A Resource Manager: Guides/ImplementingAResourceManager.md
  - Troubleshooting: Guides/Troubleshooting.md
  - Listening for Pipeline Events: Guides/PipelineEvents.md
  - Advanced Settings: Guides/AdvancedSettings.md
  - Adding to Class Path: Guides/ExtendingClassPath.md
  - Pre-allocating Resources for Jobs: Guides/PreallocatedJobs.md
  - Integration with Gitlab: Guides/Gitlab.md
  - Integration with JMS / Queuing Systems: Guides/JMS.md
  - Using Bpipe with Amazon Web Services (AWS/EC2): Guides/AWS.md
  - Using Bpipe with Google Cloud (GCS): Guides/GoogleCloud.md
  - Running Commands in Containers: Guides/Containers.md
- Examples:
  - Paired End Alignment: Examples/PairedEndAlignment.md
  - RNA Seq Corset: Examples/RNASeqCorset.md
  - WGS Variant Calling: Examples/WGSVariantCalling.md
- Releases:
  - 0.9.11 (latest): Releases/0.9.11.md
  - 0.9.10: Releases/0.9.10.md
  - 0.9.9.9: Releases/0.9.9.9.md
  - 0.9.9.8: Releases/0.9.9.8.md
  - 0.9.9.7: Releases/0.9.9.7.md
  - 0.9.9.6: Releases/0.9.9.6.md
  - 0.9.9.5: Releases/0.9.9.5.md
  - 0.9.9.4: Releases/0.9.9.4.md
  - 0.9.9.3: Releases/0.9.9.3.md
