site_name: Bpipe Documentation
repo_url: https://github.com/ssadedin/bpipe
pages:
- ['index.md', 'Welcome!']
- ['Overview/Introduction.md','Overview','Introduction']
- ['Overview/ComparisonToWorkflowTools.md','Overview','Comparison To Workflow Tools']
- ['Overview/InstallInstructions.md','Overview','Install Instructions']
- ['Guides/Troubleshooting.md','Overview','Troubleshooting']
- ['Tutorials/Hello,World.md','Tutorials','Hello, World']
- ['Tutorials/ExampleWithInputsAndOutputs.md','Tutorials','Example With Inputs And Outputs']
- ['Tutorials/RealPipelineTutorial.md','Tutorials','Real Pipeline Tutorial']
- ['Examples/PairedEndAlignment.md','Examples','Paired End Alignment']
- ['Examples/RNASeqCorset.md','Examples','RNA Seq Corset']
- ['Examples/WGSVariantCalling.md','Examples','WGS Variant Calling']
- ['Commands/Commands.md','Bpipe utility','Using the bpipe command']
- ['Guides/Logging.md','Bpipe utility','Logging']
- ['Guides/Modules.md','Bpipe utility','Modules']
- ['Guides/Notifications.md','Bpipe utility','Notifications']
- ['Guides/Regions.md','Bpipe utility','Regions']
- ['Guides/Reports.md','Bpipe utility','Reports']
- ['Guides/ResourceManagers.md','Bpipe utility','Resource Managers']
- ['Guides/ToolVersionDatabase.md','Bpipe utility','Tool Version Database']
- ['Guides/Trash.md','Bpipe utility','Trash']
- ['Language/About.md','Bpipe language','About']
- ['Language/BpipeVariables.md','Bpipe language','Bpipe Variables']
- ['Language/ParallelTasks.md','Bpipe language','Parallel Tasks']
- ['Language/BranchVariables.md','Bpipe language','Branch Variables']
- ['Language/Check.md','Bpipe language','Check']
- ['Language/Chr.md','Bpipe language','Chr']
- ['Language/Directories.md','Bpipe language','Directories']
- ['Language/Doc.md','Bpipe language','Doc']
- ['Language/Exec.md','Bpipe language','Exec']
- ['Language/ExtensionSyntax.md','Bpipe language','Extension Syntax']
- ['Language/Fail.md','Bpipe language','Fail']
- ['Language/File.md','Bpipe language','File']
- ['Language/Filter.md','Bpipe language','Filter']
- ['Language/Forward.md','Bpipe language','Forward']
- ['Language/From.md','Bpipe language','From']
- ['Language/Glob.md','Bpipe language','Glob']
- ['Language/Grep.md','Bpipe language','Grep']
- ['Language/Home.md','Bpipe language','Home']
- ['Language/Load.md','Bpipe language','Load']
- ['Language/Multi.md','Bpipe language','Multi']
- ['Language/Output.md','Bpipe language','Output']
- ['Language/Prefix.md','Bpipe language','Prefix']
- ['Language/Produce.md','Bpipe language','Produce']
- ['Language/R.md','Bpipe language','R']
- ['Language/Reference.md','Bpipe language','Reference']
- ['Language/Segments.md','Bpipe language','Segments']
- ['Language/Send.md','Bpipe language','Send']
- ['Language/Succeed.md','Bpipe language','Succeed']
- ['Language/Transform.md','Bpipe language','Transform']
- ['Language/Using.md','Bpipe language','Using']
- ['Language/Variables.md','Bpipe language','Variables']
- ['Language/preserve_-in_-pipeline.md','Bpipe language','preserve_-in_-pipeline']
- ['Language/requires.md','Bpipe language','requires']
- ['Language/uses.md','Bpipe language','uses']
- ['Language/var.md','Bpipe language','var']
- ['Development/DevelopmentSetup.md','Development','Development Setup']
- ['Development/DocumentationStyle.md','Development','Documentation Style']
- ['Development/ImplementingAResourceManager.md','Development','Implementing A Resource Manager']
markdown_extensions: [gfm]
